### ISSUE TITLE
Decryption doesn't work in PHP 5.5

### ISSUE THREAD

**Issue by ntoonio** [RNCryptor/RNCryptor-php#15]
While I was developing locally it worked perfectly. But once I moved the code to my server which has version 5.5 it doesn't work. It's not possible to update php.

Does RNCryptor still support 5.5, or should I find something else?

**Comment by ntoonio** [comment]
I decided to use another method. This thread can be closed

**Comment by curtisdf** [comment]
I realize my response may be too late in coming, but this library *is* supported in PHP 5.5.  This is demonstrated in [TravisCI](https://travis-ci.org/RNCryptor/RNCryptor-php).

Since you haven't shared what the specific problem was, I can only speculate that maybe this library's Composer dependencies were not loaded.  PHP < 5.5.0 lacks the `hash_pbkdf2` function, so we use a Composer dependency library to polyfill it.  If your local environment was >= 5.5.0 then that could explain why it worked there but not in Production.
