### ISSUE TITLE
Two Vulnerabilities in One Line

### ISSUE THREAD

**Issue by paragonie-scott** [RNCryptor/RNCryptor-php#5]
[This line of code has two cryptographic vulnerabilities](https://github.com/RNCryptor/RNCryptor-php/blob/f7ab514209fe476c4aa83a1df1fe9bb655e9e9b0/lib/RNCryptor/Decryptor.php#L99).

1. [The PHP "magic hash" evaluation flaw](http://blog.astrumfutura.com/2015/05/phps-magic-hash-vulnerability-or-beware-of-type-juggling)
2. [String comparison is vulnerable to timing attacks](http://blog.ircmaxell.com/2014/11/its-all-about-time.html)

I'd suggest replacing it with `hash_equals()`.

A [MIT licensed polyfill for `hash_equals()`](https://github.com/sarciszewski/php-future) already exists.

**Comment by paragonie-scott** [comment]
Is there any interest in fixing this?

**Comment by rnapier** [comment]
My PHP background is weak, and I haven't heard from @curtisdf in a while. I've asked a colleague of mine with much more PHP experience to take a look. I'd also be happy to look at a pull request.

Thanks for the issue.

**Comment by curtisdf** [comment]
Hi @rnapier.  Sorry for being AWOL.  I wasn't receiving any emails about RNCryptor so it was out of sight out of mind.

I have migrated the project to use hash_equals() along with the polyfill library @paragonie-scott mentioned.  I also took the opportunity to fix up our TravisCI configs.  Since PHP 5.4 is at EOL, I have moved the minimum supported PHP version to 5.5.  I also added support for testing in PHP7.

We are now at version 3.1.0.
