### ISSUE TITLE
How to be with hash_equals() on PHP 5.5.9 or lower

### ISSUE THREAD

**Issue by JavaMachine** [RNCryptor/RNCryptor-php#7]
We have implemented your library to our server... and it seems our version of PHP differs from required version in your library...

I have found some of the Backward Compatibility Workarounds in [User Contribution Notes](http://php.net/manual/en/function.hash-equals.php) ... But I have doubts about safety concerns.

For now we are using following [workaround](http://php.net/manual/en/function.hash-equals.php#117101)
Please could you suggest your optimal and safe way to do this...

Thanks in advance...

**Comment by curtisdf** [comment]
RNCryptor-php already supports PHP 5.5.  We have [passing unit tests](https://travis-ci.org/RNCryptor/RNCryptor-php) for it as well.

Are you using the latest version of our library?  It also includes a dependency on [sarciszewski/php-future](https://github.com/sarciszewski/php-future) which is a polyfill that supplies for the lack of `hash_equals()` in earlier versions of PHP.  Are you using Composer to manage dependencies and autoloading?  Otherwise you will need to read composer.json and install the dependencies yourself.
